const demo=`La pioggia aveva smesso da poco, ma il selciato conservava ancora la luce del temporale. Marta rimase davanti alla porta senza bussare.\n\nAveva immaginato quel momento per undici anni. Nelle sue versioni migliori, entrava senza paura. In quelle peggiori, non arrivava mai fin lì.\n\nDall'altra parte qualcuno spostò una sedia. Marta strinse la lettera nella tasca del cappotto. Il foglio era ormai morbido agli angoli, consumato da tutte le volte in cui aveva deciso di non leggerlo.`;
let state=JSON.parse(localStorage.getItem('museState')||'null')||{title:'Il mio romanzo',genre:'Narrativa contemporanea',goal:80000,text:demo};
const main=document.querySelector('#main'); const save=()=>localStorage.setItem('museState',JSON.stringify(state));
const head=(k,t,s)=>`<div class='hero'><div><div class='eyebrow'>${k}</div><h1>${t}</h1><div class='sub'>${s}</div></div><button class='btn'>Esporta progetto</button></div>`;
const views={
home(){return `${head('IL TUO STUDIO','Scrivi con coraggio.','Riscrivi con precisione.')}
<div class='project'><div class='card'><div class='eyebrow'>PROGETTO ATTIVO</div><h2>${state.title}</h2><p>${state.genre} · Prima stesura</p><div class='progress'><i></i></div><div class='metrics'><div><strong>${state.text.split(/\\s+/).length.toLocaleString('it')}</strong><span>PAROLE</span></div><div><strong>42%</strong><span>OBIETTIVO</span></div><div><strong>12</strong><span>CAPITOLI</span></div></div></div><div class='card'><div class='eyebrow'>INSIGHT</div><h3>La tensione cresce bene</h3><p>Il conflitto implicito funziona. Nel prossimo capitolo evita di spiegare troppo presto la ragione della lettera.</p><button class='btn' data-go='editor'>Apri analisi →</button></div></div>
<div class='grid4'>${[['muse','✦','Muse','Ideazione, tema, conflitto e domande che aprono possibilità.'],['studio','✒','Studio','Scrivi senza distrazioni con il Master Editor al tuo fianco.'],['editor','✓','Editor','Critique, line edit e interventi prioritari.'],['publisher','↗','Publisher','Pitch, sinossi, positioning e percorso editoriale.']].map(x=>`<div class='card mode' data-go='${x[0]}'><div class='eyebrow'>${x[1]}</div><b>${x[2]}</b><p>${x[3]}</p></div>`).join('')}</div><div class='quote'>“Write with the door closed, rewrite with the door open.” <small>— Stephen King</small></div>`},
studio(){return `<div class='workspace'><div class='tree'><div class='eyebrow'>MANOSCRITTO</div><h3>${state.title}</h3><small>ATTO I</small><button>Cap. 1 — Il ritorno</button><button class='sel'>Cap. 2 — La lettera</button><button>Cap. 3 — Il debito</button><br><small>ATTO II</small><button>Cap. 4 — La frattura</button><button>＋ Nuova scena</button></div><div class='writing'><div class='toolbar'><span>Capitolo 2 · La lettera</span><span id='wc'></span></div><textarea id='manuscript'>${state.text}</textarea></div><div class='ai'><div class='eyebrow'>MASTER EDITOR</div><h3>Lavora sul testo</h3><p>Intervengo sulla pagina senza sostituirmi alla tua voce.</p><div class='chips'>${['Analizza scena','Rendi più incisivo','Mostra, non raccontare','Controlla POV','Taglia il superfluo','Aumenta tensione'].map(x=>`<button class='chip' data-ai='${x}'>${x}</button>`).join('')}</div><div class='ai-result' id='aiResult'><b>Pronto.</b><p>Seleziona un intervento. Le modifiche resteranno proposte finché non le accetti.</p></div></div></div>`},
muse(){return `${head('MUSE','Trova il cuore della storia.','Non generare rumore: trova la domanda che vale un romanzo.')}${formCards([['Premessa','Una donna torna nella casa che ha lasciato undici anni prima per consegnare una lettera mai aperta.'],['Tema','Quanto della nostra identità nasce dalle cose che scegliamo di non sapere?'],['Conflitto','Marta vuole conoscere la verità, ma scoprirla potrebbe distruggere il solo rapporto familiare che le resta.'],['Posta in gioco','Perdere la sorella oppure continuare a vivere dentro una menzogna.'],['E se…?','E se la lettera non fosse destinata a Marta?'],['Domanda editoriale','Qual è la verità che Marta desidera conoscere e, nello stesso tempo, spera segretamente sia falsa?']])}`},
characters(){return `${head('STORY BIBLE','Personaggi','Desideri, ferite e contraddizioni prima delle etichette.')}${formCards([['Personaggio','Marta Serra'],['Desiderio esterno','Scoprire perché suo padre se ne andò.'],['Bisogno interno','Accettare che capire non significa necessariamente perdonare.'],['Ferita','Abbandono a sedici anni.'],['Paura','Essere uguale al padre.'],['Segreto','Ha già letto una parte della lettera anni prima.']])}`},
architecture(){return `${head('ARCHITETTURA','La forma della storia','La struttura deve servire la storia, non dominarla.')}<div class='section-grid'><div class='card'><h3>Atto I · Promessa</h3><p>Ritorno · Lettera · Debito</p><div class='progress'><i style='width:80%'></i></div></div><div class='card'><h3>Atto II · Pressione</h3><p>Frattura · Rivelazione · Perdita</p><div class='progress'><i style='width:55%'></i></div></div><div class='card'><h3>Atto III · Scelta</h3><p>Confronto · Verità · Conseguenza</p><div class='progress'><i style='width:25%'></i></div></div></div><div class='card' style='margin-top:15px'><h3>Curva di tensione</h3><p>Il centro del secondo atto necessita di una conseguenza irreversibile. Non aggiungere semplicemente un ostacolo: cambia il costo della scelta.</p></div>`},
editor(){return `${head('CRITIQUE EDITING','Diagnosi prima della cura.','Priorità chiare, interventi motivati, nessun punteggio finto-scientifico.')}<div class='project'><div class='card'><h3>Profilo del capitolo</h3>${['Chiarezza','Ritmo','Tensione','Voce','Dialoghi','Coerenza POV'].map(x=>`<div class='score'><span>${x}</span><i></i></div>`).join('')}</div><div class='card'><h3>Priorità</h3><div class='issue'><span class='tag'>IMPORTANTE</span><h3>La seconda frase spiega troppo</h3><p><b>Perché conta:</b> anticipa un’emozione che la scena potrebbe far percepire attraverso esitazione e gesto.</p></div><div class='issue'><span class='tag'>RIFINITURA</span><h3>Immagine efficace da proteggere</h3><p>“Il foglio era ormai morbido agli angoli” rende fisico il tempo trascorso. Non appesantirla.</p></div></div></div>`},
continuity(){return `${head('CONTINUITÀ','Ricorda ciò che il romanzo promette.','Fatti, date, oggetti e regole del mondo in un’unica memoria narrativa.')}<div class='section-grid'>${[['Marta Serra','34 anni · tornata dopo 11 anni'],['La lettera','Busta crema · mai aperta completamente'],['Casa Serra','Via del Porto · porta verde'],['Timeline','Cap. 1: 18 ottobre · sera'],['Promessa narrativa','Perché il padre è scomparso?'],['Possibile conflitto','Cap. 1 dice “dieci anni”; Cap. 2 dice “undici”.']].map(x=>`<div class='card'><div class='eyebrow'>${x[0]}</div><p>${x[1]}</p></div>`).join('')}</div>`},
publisher(){return `${head('PUBLISHER','Porta il libro al lettore giusto.','Posizionamento editoriale senza trasformare il romanzo in un prodotto senz’anima.')}${formCards([['Genere','Narrativa contemporanea / family drama'],['Lettore','Adulti interessati a segreti familiari, memoria e identità.'],['Logline','Dopo undici anni lontana da casa, una donna torna per consegnare una lettera che potrebbe spiegare l’abbandono del padre — e distruggere ciò che resta della sua famiglia.'],['Pitch 30 secondi','Un romanzo intimo sul prezzo della verità e sulle bugie che ereditiamo.'],['Comp titles','Da validare con dati editoriali recenti.'],['Percorso','Valutare editoria tradizionale dopo revisione strutturale e beta reading.']])}`}}
function formCards(items){return `<div class='section-grid'>${items.map(([a,b])=>`<div class='card field'><label>${a.toUpperCase()}</label><textarea>${b}</textarea></div>`).join('')}</div>`}
function render(v='home'){main.innerHTML=views[v]();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>render(b.dataset.go));if(v==='studio'){let ta=document.querySelector('#manuscript'),wc=document.querySelector('#wc');let count=()=>wc.textContent=ta.value.trim().split(/\\s+/).filter(Boolean).length+' parole · salvato';count();ta.oninput=()=>{state.text=ta.value;save();count()};document.querySelectorAll('[data-ai]').forEach(b=>b.onclick=()=>simulateAI(b.dataset.ai))}}
function simulateAI(action){let r=document.querySelector('#aiResult');let map={'Analizza scena':'<b>Diagnosi breve</b><p>La scena ha un buon oggetto-tensione: la lettera. Il rischio è spiegare il passato prima che il lettore abbia sentito il peso del presente.</p><b>Domanda</b><p>Cosa perderebbe Marta se bussasse davvero?</p>','Rendi più incisivo':'<b>Proposta</b><p>“Marta rimase davanti alla porta. Non bussò.”</p><p>Più netto, ma conserva l’originale se preferisci un ritmo più contemplativo.</p>','Mostra, non raccontare':'<b>Punto da valutare</b><p>“Aveva immaginato quel momento…” racconta direttamente. Potresti far emergere le prove mentali attraverso un gesto o una falsa partenza.</p>','Controlla POV':'<b>POV coerente</b><p>La focalizzazione resta aderente a Marta. Nessuna intrusione evidente nella mente di altri personaggi.</p>','Taglia il superfluo':'<b>Taglio possibile</b><p>“ancora” in “conservava ancora la luce” può essere eliminato senza perdita.</p>','Aumenta tensione':'<b>Leva di tensione</b><p>Il rumore della sedia è forte. Ritarda di una frase l’informazione sulla lettera e lascia che Marta interpreti quel suono prima di agire.</p>'};r.innerHTML=map[action]||''}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>render(b.dataset.view));document.querySelector('#newProject').onclick=()=>{if(confirm('Creare un nuovo progetto demo?')){state={title:'Nuovo romanzo',genre:'Da definire',goal:80000,text:''};save();render('home')}};render();
